#define SOKOL_IMPL
#if defined(_MSC_VER)
#define SOKOL_D3D11
#define SOKOL_LOG(str) OutputDebugStringA(str)
#elif defined(__EMSCRIPTEN__)
#define SOKOL_GLES2
#elif defined(__APPLE__)
// NOTE: on macOS, sokol.c is compiled explicitly as ObjC 
#define SOKOL_METAL
#else
#define SOKOL_GLCORE33
#endif

#ifndef __GNUC__
#define __attribute__(unused)
#endif

#define SOKOL_WIN32_FORCE_MAIN
#include "sokol/sokol_app.h"
#include "sokol/sokol_time.h"
#include "sokol/sokol_gfx.h"
#include "sokol/sokol_glue.h"

#include <math.h>
#include "math.h"

#include "build/shaders.glsl.h"

#define OFFSCREEN_SAMPLE_COUNT (4)

static struct {
  float rx, ry;
  struct {
    sg_buffer ibuf, vbuf;
    sg_pass_action pass_action;
    sg_pipeline pip;
  } mesh;
} state;

/* can be called once on initialization */
void mesh_init(void) {
  /* mesh pass action */
  state.mesh.pass_action = (sg_pass_action) {
    .colors[0] = { .action = SG_ACTION_CLEAR, .value = { 0.25f, 0.25f, 0.25f, 1.0f } },
    .colors[1] = { .action = SG_ACTION_CLEAR, .value = { 0.00f, 0.00f, 0.00f, 0.0f } },
  };

  state.mesh.pip = sg_make_pipeline(&(sg_pipeline_desc) {
    .layout = {
      .attrs = {
        [ATTR_mesh_vs_position].format = SG_VERTEXFORMAT_FLOAT3,
        [ATTR_mesh_vs_color0].format   = SG_VERTEXFORMAT_FLOAT4
      }
    },
    .shader = sg_make_shader(mesh_shader_desc(sg_query_backend())),
    .index_type = SG_INDEXTYPE_UINT16,
    .cull_mode = SG_CULLMODE_FRONT,
    .depth = {
      .write_enabled = true,
      .compare = SG_COMPAREFUNC_LESS_EQUAL,
    },
  });
}

void init(void) {
  sg_setup(&(sg_desc){
    .context = sapp_sgcontext()
  });

  /* cube vertex buffer */
  float vertices[] = {
    -1.0, -1.0, -1.0,   1.0, 0.0, 0.0, 1.0,
    1.0, -1.0, -1.0,   1.0, 0.0, 0.0, 1.0,
    1.0,  1.0, -1.0,   1.0, 0.0, 0.0, 1.0,
    -1.0,  1.0, -1.0,   1.0, 0.0, 0.0, 1.0,

    -1.0, -1.0,  1.0,   0.0, 1.0, 0.0, 1.0,
    1.0, -1.0,  1.0,   0.0, 1.0, 0.0, 1.0,
    1.0,  1.0,  1.0,   0.0, 1.0, 0.0, 1.0,
    -1.0,  1.0,  1.0,   0.0, 1.0, 0.0, 1.0,

    -1.0, -1.0, -1.0,   0.0, 0.0, 1.0, 1.0,
    -1.0,  1.0, -1.0,   0.0, 0.0, 1.0, 1.0,
    -1.0,  1.0,  1.0,   0.0, 0.0, 1.0, 1.0,
    -1.0, -1.0,  1.0,   0.0, 0.0, 1.0, 1.0,

    1.0, -1.0, -1.0,    1.0, 0.5, 0.0, 1.0,
    1.0,  1.0, -1.0,    1.0, 0.5, 0.0, 1.0,
    1.0,  1.0,  1.0,    1.0, 0.5, 0.0, 1.0,
    1.0, -1.0,  1.0,    1.0, 0.5, 0.0, 1.0,

    -1.0, -1.0, -1.0,   0.0, 0.5, 1.0, 1.0,
    -1.0, -1.0,  1.0,   0.0, 0.5, 1.0, 1.0,
    1.0, -1.0,  1.0,   0.0, 0.5, 1.0, 1.0,
    1.0, -1.0, -1.0,   0.0, 0.5, 1.0, 1.0,

    -1.0,  1.0, -1.0,   1.0, 0.0, 0.5, 1.0,
    -1.0,  1.0,  1.0,   1.0, 0.0, 0.5, 1.0,
    1.0,  1.0,  1.0,   1.0, 0.0, 0.5, 1.0,
    1.0,  1.0, -1.0,   1.0, 0.0, 0.5, 1.0
  };
  state.mesh.vbuf = sg_make_buffer(&(sg_buffer_desc){
    .data = SG_RANGE(vertices),
    .label = "cube-vertices"
  });

  /* create an index buffer for the cube */
  uint16_t indices[] = {
    0, 1, 2,  0, 2, 3,
    6, 5, 4,  7, 6, 4,
    8, 9, 10,  8, 10, 11,
    14, 13, 12,  15, 14, 12,
    16, 17, 18,  16, 18, 19,
    22, 21, 20,  23, 22, 20
  };
  state.mesh.ibuf = sg_make_buffer(&(sg_buffer_desc){
    .type = SG_BUFFERTYPE_INDEXBUFFER,
    .data = SG_RANGE(indices),
    .label = "cube-indices"
  });

  mesh_init();
}

static void event(const sapp_event *ev) {
  switch (ev->type) {
    case (SAPP_EVENTTYPE_KEY_DOWN): {
      if (ev->key_code == SAPP_KEYCODE_ESCAPE)
        sapp_request_quit();
      if (ev->key_code == SAPP_KEYCODE_W)
        state.rx += 0.03f;
      if (ev->key_code == SAPP_KEYCODE_S)
        state.rx -= 0.03f;
      if (ev->key_code == SAPP_KEYCODE_A)
        state.ry += 0.03f;
      if (ev->key_code == SAPP_KEYCODE_D)
        state.ry -= 0.03f;
    } break;
  }
}

void frame(void) {
  /* NOTE: the vs_params_t struct has been code-generated by the shader-code-gen */
  mesh_vs_params_t vs_params;
  const float w = sapp_widthf();
  const float h = sapp_heightf();
  Mat4 proj = perspective4x4(1.047f, w/h, 0.01f, 10.0f);
  Vec3 eye = mul3_f(vec3(
    cosf(state.rx)*sinf(state.ry),
    sinf(state.rx),
    cosf(state.rx)*cosf(state.ry)
  ), 6.0f);
  Mat4 view = look_at4x4(eye, vec3_f(0.0f), vec3_y);
  Mat4 view_proj = mul4x4(proj, view);

  vs_params.mvp = view_proj;

  sg_begin_default_pass(&state.mesh.pass_action, (int)w, (int)h);
  sg_apply_pipeline(state.mesh.pip);
  sg_apply_bindings(&(sg_bindings) {
    .vertex_buffers[0] = state.mesh.vbuf,
    .index_buffer = state.mesh.ibuf
  });
  sg_apply_uniforms(SG_SHADERSTAGE_VS, SLOT_mesh_vs_params, &SG_RANGE(vs_params));
  sg_draw(0, 36, 1);
  sg_end_pass();

  sg_commit();
}

void cleanup(void) {
  sg_shutdown();
}

sapp_desc sokol_main(int argc, char* argv[]) {
  (void)argc;
  (void)argv;
  return (sapp_desc){
    .init_cb = init,
    .frame_cb = frame,
    .cleanup_cb = cleanup,
    .event_cb = event,
    .width = 800,
    .height = 600,
    .sample_count = OFFSCREEN_SAMPLE_COUNT,
    .gl_force_gles2 = true,
    .window_title = "Bloom MVP",
    .icon.sokol_default = true,
  };
}
